name: Upload Sample Artifact to JFrog Artifactory

on:
  workflow_dispatch:

jobs:
  upload-artifact:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up JFrog CLI
      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        with:
          version: latest

      # Create sample artifact
      - name: Create sample artifact
        run: |
          mkdir -p build/output
          echo "Sample artifact content" > build/output/sample.txt
          zip -r sample-artifact.zip build/

      # Configure JFrog CLI using GitHub secrets
      - name: Configure JFrog CLI
        run: |
          jf config add artifactory-server \
            --url ${{ secrets.JF_URL }} \
            --access-token ${{ secrets.JF_ACCESS_TOKEN }} \
            --interactive=false

      # Upload artifact to Artifactory
      - name: Upload artifact
        run: |
          jf rt upload "sample-artifact.zip" "my-repo/path/to/artifacts/" \
            --build-name="sample-build" \
            --build-number="${{ github.run_number }}"
