name: Build OpenTelemetry Collector Contrib

on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up JFrog CLI
      - name: ocb download
        run: |
          curl --proto '=https' --tlsv1.2 -fL -o ocb \
          https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/cmd%2Fbuilder%2Fv0.138.0/ocb_0.138.0_linux_amd64
          chmod +x ocb
          pwd && ls -la
